### ISSUE TITLE
Char stucks when attacking with high atk. speed

### ISSUE THREAD

**Issue by Sponer** [L2J/L2J_Server#101]
Hello,

I see this problem years from now...
When a player is auto-attacking something (ex. a NPC),
after a short duration, the char stops listen to anything and it just keeps attacking... like it's not responding anymore...
Last time I saw this on my server while testing something...
I was auto attacking a npc with 2600 atk. speed with a blunt weapon... after arround 10-20 seconds i let it auto=attacking the npc, the char just stopped responding to any other packet... (move, stop, lose-target, exit, restart, change weapon.... anything)

**Comment by Sacrifice78** [comment]
Yes. I also saw this problem for years and it was for that reason in the database, but also has to do with many factors such as (32 or 64 bit) operating system and amount of memory allocated to the game server (remember that operating systems 32-bit support only 1536MB of RAM for java or less). Another interesting setting is added to the starting line .bat or .sh the parameter -Xincgc but I think it is allowed to work alone java and to make himself the type of garbage collector for the heap and stuff.

**Comment by Sacrifice78** [comment]
But for years I have not seen this symptom. In my local test server (127.0.0.1) I have assigned 4096Mb of RAM for java in .bat file starting and yes... the operating system is 64-bit. I have not noticed that symptom recently, so I ask...: Has this symptom appear again?. For so... possibly the machine that runs the server is on the limit of the maximum hardware architecture (technically it says so). Without knowing such data it can not be clearly diagnose such errors.

**Comment by Sponer** [comment]
I'm running my local server with 6GB of RAM and AggressiveOpts argument enabled, also I run in windows 7 64bit....
It can't be machine's problem...

**Comment by Sacrifice78** [comment]
Delete -AggressiveOpts parameter and leave Java that do his job by himself. 6Gb its too much... with 4Gb totally sufficient, believe me.

**Comment by Sacrifice78** [comment]
Think about this parameter. Copied and pasted from java documentation.

-XX:+AggressiveOpts 
Turns on point performance optimizations that are expected to be on by default in upcoming releases. The changes grouped by this flag are minor changes to JVM runtime compiled code and not distinct performance features (such as BiasedLocking and ParallelOldGC). This is a good flag to try the JVM engineering team's latest performance tweaks for upcoming releases. Note: this option is experimental! The specific optimizations enabled by this option can change from release to release and even build to build. You should reevaluate the effects of this option with prior to deploying a new release of Java.

**Comment by Sponer** [comment]
This is not any memory or Java's performance problem....
I believe it's a kind of flood in packets (too many) And if that happens, I think we should put a priority level to each packet....

**Comment by sshumilov** [comment]
Tested with default config for mysql and l2j. Not facing the problem.
Try to increase values for ThredPoolManager in General.properties.

**Comment by Sponer** [comment]
# ---------------------------------------------------------------------------
# Thread Configuration
# ---------------------------------------------------------------------------

# Extreme caution should be here, set to defaults if you do not know what you are doing.
# These could possibly hurt your servers performance or improve it depending on your server's configuration, size, and other factors.
# Default: 10
ThreadPoolSizeEffects = 6

# Default: 13
ThreadPoolSizeGeneral = 6

# Default: 2
ThreadPoolSizeEvents = 6

# Default: 2
UrgentPacketThreadCoreSize = 6

# Default: 4
GeneralPacketThreadCoreSize = 6

# Default: 4
GeneralThreadCoreSize = 6

# Default: 6
AiMaxThread = 12

# Default: 5
EventsMaxThread = 6

# Dead Lock Detector (a separate thread for detecting deadlocks).
# For improved crash logs and automatic restart in deadlock case if enabled.
# Check interval is in seconds.
# Default: True
DeadLockDetector = True

# Default: 20
DeadLockCheckInterval = 8

(I run with these settings)

**Comment by Sacrifice78** [comment]
What do you think about this settings L2J Developers?

**Comment by Sponer** [comment]
This problem happens when i auto attack and i minimize the client for a while...
For example, try hitting a npc with 2600 atk. speed and minimize the client for 10 seconds... then the player stops responding...

**Comment by sshumilov** [comment]
I'll check with window minimizing

**Comment by Sponer** [comment]
btw is there any site to read more about ThreadPool?

**Comment by sshumilov** [comment]
Yes. Oracle java docs

**Comment by Zoey76** [comment]
How are you getting that 2600 atk speed?

**Comment by Sponer** [comment]
Edited Super Haste lv4 :P

**Comment by Sponer** [comment]
So did anyone test for this problem? is it happening to you?

**Comment by Sacrifice78** [comment]
It is normal have "lag" when you minimize the window of the lineage. The machine frees RAM for something else that require. When you maximize lineage window again, char stop some secs till refresh processes. I want to remember that are unrecomended run server on normal operating systems. We must install server on Server Operating systems for best performance.

For me... are working all perfect!. With lastes versions and geodata. I dont have this type if issue or at least i see normal functionality.

**Comment by Sacrifice78** [comment]
Non Server operating systems are for test only purposes not for open to public.

**Comment by Sponer** [comment]
Who said I have a live server on my pc? ;)

**Comment by Sacrifice78** [comment]
So to me that nothing happens. Its more... never I touched threading for nothing... must be something rare on your local machine wrong configured not relative to server. I think ;)

**Comment by Sacrifice78** [comment]
Antivirus, "windoor firewall", MySQL, java... must be well... Its very difficult diagnose an issue without knows machine and all software installed, but thats personal from each one.

**Comment by sshumilov** [comment]
Tested with speed 3100. No lags with default settings.

**Comment by Sacrifice78** [comment]
@Zoey76 can you close this issue?.
