### ISSUE TITLE
Players heading still changes on teleportation.

### ISSUE THREAD

**Issue by JMD13** [L2J/L2J_Server#102]
Probably it was fixed at some point: http://www.l2jserver.com/forum/viewtopic.php?f=70&t=12272

But now it happens again.

**Comment by Zoey76** [comment]
Describe the bug correctly here, what is the issue?

**Comment by JMD13** [comment]
When you teleport via the gatekeeper, tha characters heading changes. On l2off the character does not change its heading while teleporting.

**Comment by JMD13** [comment]
Also check the topic i mentioned in the initia post, it might give you better insight in the issue.
