### ISSUE TITLE
AntiFeedManager Fix

### ISSUE THREAD

**Issue by Sponer** [L2J/L2J_Server#111]
When a player's IP (ex. 127.0.0.1) is in whitelist with 0 extra slots (ex. 127.0.0.1,0);
This IP has -1 slot in everything (GAME, EVENTS, OLYMPIAD).
Because of this line...
num = num == 0 ? -1 : num;

Tested Fix:
num = num == 0 ? 0 : num;

**Comment by Sacrifice78** [comment]
a player may not have the IP 127.0.0.1. It's technically impossible.

**Comment by Sponer** [comment]
this change doesn't affect any other player except from those who are in whitelist with 0 extra slots

**Comment by Zoey76** [comment]
We need to check if that doesn't break the protection.

**Comment by Sponer** [comment]
It doesn't... it's very simple... the code is completely the same...
num is the value of extra slots for each IP address in whitelist...
if value is 0, it was returing -1 (slot)
else if value is >=1, it's returning value...
I just made it, if value is 0, return 0 instead of -1
