### ISSUE TITLE
Bow/crossbow attack time

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#115]
I notice that when someone knocks an arrow
when bar ends there is a small delay till new attack starts
its like 500ms-1s delay

And one more thing every time someone knock arrow and ss are enabled in every hit there is a spam that char enabled ss

**Comment by Pavel2451** [comment]
yes, its true. Comfired

**Comment by Zealar** [comment]
Fixed in https://github.com/L2J/L2J_Server/commit/0e0587c183f1d398a0c61dc3491944ceec70409d
