### ISSUE TITLE
Attribute calculation bonus is wrong!

### ISSUE THREAD

**Issue by Pavel2451** [L2J/L2J_Server#131]
Hello. We found bad calculation for Attribute bonus...

CONFIRMED by me :100: 

So.. example:

1/ Monster Att, Rezist Water 100     -VS-     Player with NOT attributed weapon:
70 dmg +-

2/ Same monster   -VS-     player with attribute  water attack on weapon +20 bonus
30 dmg +-

3/ Same monster   -VS-     player with attribute water attack on weapon + 120 bonus 
80 dmg+-

**Comment by luksdlt92** [comment]
I'm not an expert about attribute points, but maube the monster has resist to that element?

**Comment by Pavel2451** [comment]
:+1: 
but please read again example 1,2,3

And where is power of weapon ? If is Attributed...

**Comment by luksdlt92** [comment]
If you see the code, it's better have a weapon without element instead of an element attribute that monster resists. I think that's why exists skills without element.

If it's retail or not, i'm not sure, that's why i told you if you tested in retail :dancers:

**Comment by Pavel2451** [comment]
I dont have any chance to test on L2Off Hi5...

But logically.. if now is retail like.. so enchanted weapons.. is not useful.

So I think it must first calculate classics dmg... and later must calculate att. dmg..

If player have lower atatribute.. it give nothing bonus else give bonus...

**Comment by valanths1990** [comment]
this is invalid cause you have lower water attack in your weapon than monster water resist
thats why when you go to 120 water attack damage is higher
water attack 120 > water resist 100 so damage will be bigger
water attack 70 < water resist 100 so damage will be lower

**Comment by luksdlt92** [comment]
@Pavel2451 Exactly, that's why select the element is very important :dart: 
Maybe @Zealar knows the true :smile:

**Comment by Pavel2451** [comment]
Yeah I know.. But example Ekimus rezistance is very high.. so, better is attacking without attributes :-D

**Comment by luksdlt92** [comment]
@Pavel2451 Probably

**Comment by Pavel2451** [comment]
Freya boss 300 Rezst Attribute.. so She will play with you

**Comment by sandpants** [comment]
From what I am reading here http://forum.pmfun.com/viewtopic.php?t=36778
Damage  reduction caused by -N resist difference (or simply higher defense value than attack) is capped at 20%.
So you can reduce damage by going 20 attack -100 defense, but damage won't be less than x0.8.
It does seem daft - to force the player to use either non attributed weapons or very high attribute weapons. Makes the interval in between useless...

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_Server/commit/67acb27e51ea1fa7e2b6fe2be321ffd2fb3e3691
