### ISSUE TITLE
Bow/crossbow attack time

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#133]
There are still issues

For example you hit normal one mob

When your throw the arrow you can move in that time when red line ends- dissappear
if you press attack again you can see that there is a delay of 1 second

This only happens if you click to move when red line is at half
and when dissapear attack again, char stop move and might take the next hit with 1 second delay

**Comment by Zealar** [comment]
Cannot reproduce it.

**Comment by valanths1990** [comment]
normal attacks and press to move many times while pressing to attack something

attack - move - attack - move etc

If you still cant reproduce it lock it as invalid

**Comment by Zealar** [comment]
Nope cannot see any problem.
