### ISSUE TITLE
Skill Hide

### ISSUE THREAD

**Issue by Affinity90** [L2J/L2J_Server#135]
Skill hide need fix
![shot00000](https://cloud.githubusercontent.com/assets/15854488/11167889/9aa907aa-8b7e-11e5-8913-992636c29a30.jpg)
![shot00001](https://cloud.githubusercontent.com/assets/15854488/11167893/ae08c984-8b7e-11e5-8031-3de8af7843c3.jpg)

this should not be

**Comment by xban1x** [comment]
This was not fixed correctly. L2Object has both Invisible and Visible options. Visible should be used for skill Hide. Invisible should be used for GM hiding players or any other custom command.

**Comment by Zealar** [comment]
Why we got 2 in first place?

**Comment by UnAfraid** [comment]
isVisible can be renamed to isSpawned because its mostly what it does
