### ISSUE TITLE
Fake death: skill id: 60

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#139]
when fake death is activated and press again to deactivate
char using again fake death like an infinite loop and you cannot get rid of it unless no more mp

**Comment by Zoey76** [comment]
I think there is a post about this.

**Comment by Zoey76** [comment]
There is already https://github.com/L2J/L2J_DataPack/issues/247...

**Comment by valanths1990** [comment]
This change made fake death stop working as it should be https://github.com/L2J/L2J_Server/commit/7f170063ef10f99b68f72c593d70c6bd155d255f
