### ISSUE TITLE
Fix hero skills shoudn't apply to sub class

### ISSUE THREAD

**Issue by dragonceleste** [L2J/L2J_Server#149]
whit this change the title no load on login.

**Comment by luksdlt92** [comment]
What? ¿Qué quisiste decir?

**Comment by dragonceleste** [comment]
que cuando logeas un personaje aparece sin titulo. De clan tittle por ejemplo, entre otros. No se guarda ningun titulo.

**Comment by luksdlt92** [comment]
"Fix hero skills shoudn't apply to sub class", tiene algo que ver con el título el reporte?

**Comment by maneco2** [comment]
@dragonceleste Hero skills in sub-classe alrady fixed in https://github.com/L2J/L2J_Server/commit/10407a807415f558d8da56b27db82132beb424fa
Tible characters: check acess level! acess admin have this problem!

**Comment by Zoey76** [comment]
Let me check this againm just to be sure.
