### ISSUE TITLE
Time respawn RB

### ISSUE THREAD

**Issue by neodemio** [L2J/L2J_Server#164]
the time respawn Raid boss is bug, the time in database store is 1449597993327 for all raidboss.

**Comment by maneco2** [comment]
I do not have this problem, all the bug report no one put the version used in the post... High Five? Freya ? Interlude? :-1:

**Comment by neodemio** [comment]
I 'm using the master branch , which says that according to the description is the stable version for high five .

**Comment by Zealar** [comment]
Same is not happen to me too. Test on clean files and on develop version too.
If problem is in master update or wait till next marge between them.
