### ISSUE TITLE
Quest subclass

### ISSUE THREAD

**Issue by neodemio** [L2J/L2J_Server#167]
subclass quest can not choose a class, the quest item disappears (Elixir Mimir) but still can not choose anything, it indicates that it should get the quest item.

**Comment by Zealar** [comment]
Show current character quests

**Comment by neodemio** [comment]
the quest of the character is complete , both " feath of whisper " as "Elixir of mimir " and still can not take any subclass , the quest was made as normal, plus probe by assigning full quest to a character test and not subclase.configure works adhering a character properties to be allowed to take the subclass without quest, but still not allowed to take the sub class.

**Comment by Zoey76** [comment]
@Zealar have you checked this is currently working correctly?

**Comment by Zealar** [comment]
Yes and is working perfect guess he don't use sql update so got still old quest names in database
