### ISSUE TITLE
SoulShots

### ISSUE THREAD

**Issue by Affinity90** [L2J/L2J_Server#173]
after using soulshots removing weapons and wearing it again to re-use soulshot Off-like
Now used soulshots took the weapon and again put soulshots again no uses
![shot00020](https://cloud.githubusercontent.com/assets/15854488/11730354/29b5e4b8-9f9d-11e5-87d6-d808e2be435b.jpg)

**Comment by maneco2** [comment]
Now, soulshot's is getting saved the last time used the weapon. Attacking an NPC and you will see that the Soulshot is enabled to re-equip the weapon!

**Comment by Affinity90** [comment]
www.rpg-club.com PTS x1000
![shot00001](https://cloud.githubusercontent.com/assets/15854488/11732004/a2e3a388-9fa8-11e5-8c78-661153e5b622.jpg)

**Comment by maneco2** [comment]
Soulshot is saved in the weapon is unequipped, no need to activate it again to re-equip it is already active! Attack a target to see the Soulshot....

**Comment by Affinity90** [comment]
You think so? or it should be?

**Comment by maneco2** [comment]
Retail if you unequip the weapon and re-equipping will spend soulshots.

**Comment by Affinity90** [comment]
Thx =)
