### ISSUE TITLE
Item effect

### ISSUE THREAD

**Issue by Affinity90** [L2J/L2J_Server#174]
After removing the weapons should not write about the effect of removing weapons 
![shot00027](https://cloud.githubusercontent.com/assets/15854488/11730810/0a7623c6-9fa0-11e5-8f1a-06e8fd3336d3.jpg)

**Comment by maneco2** [comment]
Yes, confirmed.

**Comment by Affinity90** [comment]
Problem is not only in the arms of any object displays a message about removing effect it

**Comment by maneco2** [comment]
Is Corfirmed (Off Server's and Official NC)
