### ISSUE TITLE
QuestList

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#178]
wrong approach to copy one list to another

Here are some ways to copy elements from one list to another

_quests.addAll(_activeChar.getAllActiveQuests());
or 
_quests = new LinkedList<>(_activeChar.getAllActiveQuests());
or
Collections.copy(_quests, _activeChar.getAllActiveQuests());

**Comment by Zoey76** [comment]
Explain better.

**Comment by valanths1990** [comment]
if i am not wrong you cannot copy one list to another using =
_quests = _activeChar.getAllActiveQuests();

**Comment by valanths1990** [comment]
well i was wrong _quests = _activeChar.getAllActiveQuests(); this work
close it
