### ISSUE TITLE
Rune of Crystal

### ISSUE THREAD

**Issue by Affinity90** [L2J/L2J_Server#179]
If there is a rune and then do a restart appear Grade Penalty
![shot00000](https://cloud.githubusercontent.com/assets/15854488/11764535/1be9e05e-a13d-11e5-9e03-0560128e2964.jpg)
Remove item and Grade Penalty removed
![shot00001](https://cloud.githubusercontent.com/assets/15854488/11764544/610fdb84-a13d-11e5-9d11-bfb4c4e104c8.jpg)
![shot00002](https://cloud.githubusercontent.com/assets/15854488/11764545/6115b3c4-a13d-11e5-942b-b114283de08c.jpg)

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_DataPack/commit/d44264596e72806fc6faf0af2528ec8ce2c10842 thx.
