### ISSUE TITLE
Buy item long distance from the npc

### ISSUE THREAD

**Issue by maneco2** [L2J/L2J_Server#180]
L2J of items to buy long distance NPCs
Example: grocery store giran buy something ... go to the giran center and click to finalize the purchase of the item..
Tested in (Off Server's and Official NC) short-range

**Comment by valanths1990** [comment]
did you try it with non gm char?
cause i see gm chars can bypass range check

**Comment by maneco2** [comment]
normal character...

**Comment by maneco2** [comment]
@valanths1990 yes, acess level 7, are so many problems, the person to be confused :+1:
