### ISSUE TITLE
Chant of Blood Awakening

### ISSUE THREAD

**Issue by ovalefor** [L2J/L2J_Server#193]
Chant of Blood Awakening mysteriously appears in all online skills list.

**Comment by maneco2** [comment]
You have compiled L2J?

**Comment by ovalefor** [comment]
Yes, the skill does not appear often, but sometimes it appears in the character's skills list, rarely, however it appears without time or reason.

**Comment by Zoey76** [comment]
Unable to reproduce the issue.

**Comment by ovalefor** [comment]
I will make a screenshot to show what is.
