### ISSUE TITLE
How do I know which  client version should I use for the server?

### ISSUE THREAD

**Issue by codepython** [L2J/L2J_Server#194]
is there document for details of  relevant topic as this ?

**Comment by Zealar** [comment]
https://github.com/L2J/L2J_Server/branches

develop/master = High Five
Rest is named by they version

**Comment by Zoey76** [comment]
https://github.com/L2J/L2J_Server/wiki/The-Lineage-II-Client#how-do-you-know-if-your-client-works-with-the-server
