### ISSUE TITLE
Drop list FS

### ISSUE THREAD

**Issue by neodemio** [L2J/L2J_Server#195]
according to this page ( http://legacy.lineage2.com/news/highfive_03.html ), the drop list for this chronicle ( high five ) in monastery of silence the FS to drop below , Deflect Magic , Anti -Magic Armor, Sixth Sense, Expose Weak Point , Hide , Dual Dagger Mastery , Silent Mind , Seven Arrow, Final Secret , Enlightenment - Wizard / Healer , Servitor Barrier, Excessive Loyalty , Mutual Response, Meteor , Starfall , and Turn Stone and not drop any aforementioned book

**Comment by maneco2** [comment]
Duplicate https://github.com/L2J/L2J_DataPack/issues/241
