### ISSUE TITLE
Character locked

### ISSUE THREAD

**Issue by u3games** [L2J/L2J_Server#205]
Last vers devs.

It happens all the time. When making skills, the character will get stuck.

The player has to reloguear.

-------------

Sucede continuamente. Al realizar skills, el personaje se queda bloqueado. 

El jugador tiene que reloguear.

**Comment by irlex** [comment]
helpfull unstuck/soe and cancel that, or death ))
no that issue for me, but i know about )

**Comment by u3games** [comment]
Any notice... is a serious problem ...

**Comment by u3games** [comment]
On my server, players have reported this annoying error.

They say it happens with forgotten skills, type pain sedd.

**Comment by u3games** [comment]
Move to data --> https://github.com/L2J/L2J_DataPack/issues/309
