### ISSUE TITLE
bug name clan

### ISSUE THREAD

**Issue by morzingrath** [L2J/L2J_Server#209]
Hello,
(FR) Quand un joueur veux saisir un nom de clan tel que "Les Rings", ils ont "Les"
(EN) When a player want to set clan name such as " The Rings " , they have "The "

**Comment by u3games** [comment]
Only name clan (no spaces).

**Comment by xban1x** [comment]
This probably comes due to old commands which split the string by spaces to receive their arguments. Should be an easy fix...

**Comment by xban1x** [comment]
@u3games You should be able to fix this easily come on ;)
