### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by marciox25** [L2J/L2J_Server#223]
-Skill enchantment. Cooldown of the skill is beeing reseted assoon someone enchants the skill.
-Multi Skill. SkillCheck option is not working. only works on char restart. Isnt it possible to make it instantly to remove the skill as soon it detects it?

**Comment by Zealar** [comment]
About first report that is how is working. After change enchant that skill is not same anymore. If not like it disable enchant out of town.
Multi skill check is perform when skill is restore for player login/switch sub. Other way to add fake skills is fixed last changes so guess need to stop happen. Report if find way to add fake skill to player.

**Comment by marciox25** [comment]
Hello Zeelar, I Could make a temp fix for these bugs. About the new way of learning the skills is: a player that can use phx, goes for example to the npc that teaches you fishing skills, with phx he can change the ID of the fishing skill and with this he will learn a skill that he wants.

**Comment by Zealar** [comment]
I test right now try to add Zealot to my char nothing happen. Can you give some example of working skill?

**Comment by marciox25** [comment]
If you add your self a skill, the skill will only be deleted if you relog or switch class.

**Comment by Zealar** [comment]
But how, how will add it tell me the way.

**Comment by marciox25** [comment]
Using PHX. They go to the npc that learns you any skill, and they change the ID of the learned skill to the one they want. This is how they do it. But like I said, Ive found a fix for it. You may close the topic if you want

**Comment by Zealar** [comment]
I understand is PHX but how what they send? I change skill id but nothing happen you sure that is correct way, do you even test it?
