### ISSUE TITLE
Prime Shop Core Side

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#224]
Missing feature.

**Comment by Zoey76** [comment]
Since NA client doesn't support it, it's unlikely that we will be adding it anytime soon.

**Comment by Sacrifice78** [comment]
You say that because you have to edit the client (default is not enabled PrimeShop) ... no?

**Comment by maneco2** [comment]
Need edit l2.ini, set True PrimeShop :+1:

**Comment by Zealar** [comment]
Wait we need to add it at all?

**Comment by Sacrifice78** [comment]
Okok, Im working on H5 treasure chests actually. No problem.

**Comment by Zealar** [comment]
Treasure? I speak for prime shop. We need it when cannot be used without client edit?

**Comment by Sacrifice78** [comment]
Sorryp for mix threads... Just only minor info... Emmmm... About Primeshop, till I know... primeshop require to edit client yes or yes... Its just edit one boolean setting from false to true.

**Comment by Zealar** [comment]
Is still client edit no matter how much you touch. So if we done it players will start ask "i enable it on config but is not working" what will tell them ?

**Comment by Sacrifice78** [comment]
Yes. it's true... I know what you mean... well... I will close the issue of Core and Datapack if you think until can do by other methods. :+1:
