### ISSUE TITLE
Magic skill reuse delay problem must be confirmed.

### ISSUE THREAD

**Issue by uzziel7035** [L2J/L2J_Server#240]
I know that magic skills like hydroblast and hurricane have delay.

And if the cast speed is increased, then the delay is shortened.

But if the cast speed increases over a certain number of speed, maybe over 1300,

then there will be no longer difference between 1300 and 1999.

for example, now my char's cast speed is 1350 and it goes up to 1999 due to activating 

enlightenment skill. But cant figure out any difference between 1350 and 1999.

need to be confirmed.

**Comment by u3games** [comment]
change "MaxMAtkSpeed", to 4000 for example ;)

**Comment by Zealar** [comment]
Test that patch
https://gist.github.com/Zealar/4ed6302063d3ed63ddd6
Btw there is min and cannot go lower that 500ms
