### ISSUE TITLE
Worng Gatekeeper Location Elven Village

### ISSUE THREAD

**Issue by dannyperez** [L2J/L2J_Server#25]
L2J Revision Number: (how to check the rev? i update today)
L2JDP Revision Number: (how to check the rev?)
Client: Ertheia
Server: Ertheia [BETA]

1.- Wrong Gatekeeper Location in Elven Village see 
![shot00001](https://cloud.githubusercontent.com/assets/1621222/5620398/0801a90c-9502-11e4-891a-3a15d39e9758.JPG)

**Comment by Gladicek** [comment]
Elven village isnt updated yet as I know :)

**Comment by St3eT** [comment]
Elven Village is reworked in L2J/L2J_DataPack@a76acd63dbc0450c77ce6597e7d83563f7ecb54f
