### ISSUE TITLE
Adena Error

### ISSUE THREAD

**Issue by Federyco** [L2J/L2J_Server#253]
Hello and good morning, i finished to compile the server 1 day ago and now i got all running ok but, when i went to kill a mob ( no champ or Rb) it haves no drop, when i shift + click i see all drop and spoil in 0%. Raidbosses and Champion Mobs are working "good" but the normal ones doesnt drop even Adena. Can help me?

**Comment by luksdlt92** [comment]
What's the level difference between the mob and your character?

**Comment by Zealar** [comment]
Maybe bad settings?

**Comment by Federyco** [comment]
Solved, just compiled all again, the problem was editing the Rates.properties
