### ISSUE TITLE
Items count on pick up

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#255]
For example we party and we farm

if we kill one monster
and drops for example 100 adena this amount will distribute to other party member
and we will have 50 for player A and 50 player B

Now if we kill one mob and it drops 99 adena player A will get 49 and player B 49
and one goes to server :D

same will happen if one player drop 99 adena and pick them again
it will be 49 and 49 one for the server

**Comment by Zealar** [comment]
https://gist.github.com/Zealar/069307766638fbed14fa

**Comment by valanths1990** [comment]
same problem

**Comment by Zealar** [comment]
Do you apply a patch?

**Comment by valanths1990** [comment]
Yeap

**Comment by Sacrifice78** [comment]
@valanths1990 ... And?...

**Comment by valanths1990** [comment]
if you check my replies

same problem after patch

**Comment by Sacrifice78** [comment]
For this reason @Zealar ask you... :+1:

**Comment by Zealar** [comment]
Patch is working fine for me. I drop 99 adena and pickup with party of 2. Player A take 50 player B take 49.

**Comment by valanths1990** [comment]
yea my fault i didnt explain it
with your patch 99 adena is fine one player will get random +1

But if you drop 1 adena

and one of party tries to pick up
one will get 1 adena
and the other guy will get message that he earned 0 adena

http://prntscr.com/adsqtc

**Comment by Zealar** [comment]
You mess something see line 85 of the patch is give you adena only if is above 1.
Apply patch properly.

**Comment by valanths1990** [comment]
shit i dont know how i miss it...
patch is working properly ;)
