### ISSUE TITLE
Talisman with active skills are not working

### ISSUE THREAD

**Issue by Tavo22** [L2J/L2J_Server#257]
You use the talisman item skill and nothing is happening, for example talisman id 10533

	<item id="10533" type="Armor" name="Blue Talisman - P. Atk.">
		<set name="icon" val="icon.etc_talisman_i01" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="deco1" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="GOLD" />
		<set name="weight" val="150" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3487-1" />
		<set name="duration" val="65" />
		<set name="useSkillDisTime" val="6" />
	</item>

**Comment by Zealar** [comment]
Working perfect for me. Problem is somewhere in your code, tested with both normal and gm char.

**Comment by Tavo22** [comment]
Uhm i was using a clean install without any modification. I will retest.

**Comment by Zealar** [comment]
H5 last dev right?

**Comment by Tavo22** [comment]
Yes, I tested again with latest revision. I press the skill and nothing is happening but when trying to use the skill again it is saying again that there are x minutes to reuse.

**Comment by Zealar** [comment]
Is working for me hmmm. Post some images.

**Comment by Tavo22** [comment]
Found the issue, if the talisman is without mp then the skill is not working. Thanks

**Comment by Zealar** [comment]
:)
