### ISSUE TITLE
calculateRewards - double use of skills

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#259]
i dont know how to explain it correctly

Lets say we have a party and we farm

Player A hits one mob ( normal hits )
player B waits to land over hit skill

and somehow calculateRewards called for second time
check the output:
http://prntscr.com/aezqf4

ps. same thing can happen if players are not in party
but hit same target more than one players

**Comment by Zealar** [comment]
What you got on L2Attackable line 603? Seems your code got extra or is out of date.
Better post whole method and mark line 603.

**Comment by valanths1990** [comment]
it was only the logger i add nothing else changed in source
LOG.info("", new IllegalArgumentException());

i used latest develop

**Comment by Zealar** [comment]
Is rare or? Try to increase hit time for Deadly Blow (263) to 10000 and both players to start cast it on mob for can got time to hit it in same time.

**Comment by valanths1990** [comment]
in that log i post earlier only one char cast deadly blow (one time only), the other one was just hitting the mob with normal hits
if you still want me to test that you describe with high hit time let me know

**Comment by Zealar** [comment]
So you receive double log for blow cast but he use it single time?
Extends log to this one.
	LOG.info("Mob : " + this);
	LOG.info("Killer : " + lastAttacker);
	LOG.info("Killer LS : " + lastAttacker.getLastSkillCast());
	LOG.info("Mob hate player");
	for (L2Character pc : this.getHateList())
	{
		LOG.info("PC : " + pc);
	}
	LOG.info("", new IllegalArgumentException());

**Comment by valanths1990** [comment]
i have null pointer when retrieves hate list

**Comment by valanths1990** [comment]
http://prntscr.com/af0zkx
