### ISSUE TITLE
Pathfind-geodata

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#267]
i know there are reports for those things but..

We must give high priority for fix geoengine and pathfind engine

in frintezza for example in first room if you run between objects
mobs climb on the walls, and eventually drop down in textures
result: impossible to continue in next step cause they cant kill all mobs

frintezza was just an example this can happen anywhere

if you attack or follow a target and that target run between corners etc in the end player will climb on wall and eventually drop down in textures imagine that in olympiad

in geoengine
you can shoot through floors, walls in toi

you can pass through walls if you mount a wyvern or you are inside water
cause there is not check if you are inside water or fly

its almost impossible to board on ships

and so on

some issues are fixed in geoengine stabilation but still is not recommended for live servers

**Comment by Zealar** [comment]
We know about geodata problems but is not something that easy to be fixed, and more reports will not made it easier.

**Comment by valanths1990** [comment]
agree and sorry for that report
