### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nightw0lv** [L2J/L2J_Server#31]
[javac] H:\L2\workspace\L2J_Server\L2J_Server\java\com\l2jserver\gameserver\network\NpcStringId.java:25172: error: unmappable character for encoding Cp1253
    [javac] 	@ClientString(id = 1801266, message = "Small fry! I will show you true madness!β€? Hahaha!!")
    [javac] 	                                                                                 ^
    [javac] 1 error

**Comment by UnAfraid** [comment]
Pull

**Comment by Zoey76** [comment]
Shouldn't we force UTF-8 on workspace project?
