### ISSUE TITLE
no exist jars

### ISSUE THREAD

**Issue by dEROZA** [L2J/L2J_Server#48]
l2jlogin.jar and l2jserver.jar no exist in dist

**Comment by Zoey76** [comment]
I compiled last night master, freya and ertheia branches, they all compile correctly.

Be more specific with your reports.

**Comment by Zoey76** [comment]
You can find jars in proper folders:
dist/game/
dist/login/
dist/tools/

**Comment by dEROZA** [comment]
Thanks. I will try with reports =)
