### ISSUE TITLE
Crtitical bug for live server! attack problem.....

### ISSUE THREAD

**Issue by Elitovec** [L2J/L2J_Server#5]
L2J Revision Number:6652
L2JDP Revision Number:10464
Client: High Five
Server: High Five [Stable]
When i click double on player/npc/mob for autoattack (meele attack), character go close the player/npc/mob and hit ONLY once and stop! I must move and again set autoattack on palyer/npc/mob. More peoples say "It's bug with ranges."

It's unussable revision for live server with this bug! Please solve :)

**Comment by dEROZA** [comment]
+

**Comment by luksdlt92** [comment]
@Zoey76 It wasn't fixed here -> https://github.com/L2J/L2J_Server/commit/fa89b0cab2108261e775c60b72c6018127312aaf ?
