### ISSUE TITLE
Karma Bug

### ISSUE THREAD

**Issue by davion00** [L2J/L2J_Server#64]
When a player with white name (getPvPFlag ==0) kill a player that has Karma then the player with no pvp flag is getting karma.

**Comment by davion00** [comment]
Note: The PK Killer after sometime he lose the PvP Flag that he is able to be auto attack thats why it happens. Try to PK someone and wait until the PvPFlag to set to 0 on that character and then kill him while he is on karma. Then the killer will get karma.. if you take pk and someone kill you immeadietly then you will not have any problem.

**Comment by Zealar** [comment]
Seems not happen anymore.
