### ISSUE TITLE
Mobs cast own buffs on player

### ISSUE THREAD

**Issue by sshumilov** [L2J/L2J_Server#93]
Hi5 stable
L2J_Server rev: 7a2c5132bcd7fb68c4e69d96a12c5cc1081baf58
L2J_DP rev: 86da2832a2a78d297a2f14eb3b50cd4091ebb02c

1) Go to ant nest
2) Attack group of social mobs
3) Wait some time and check buffs

![screenshot from 2015-09-15 14 47 13](https://cloud.githubusercontent.com/assets/8612428/9875769/8bb42a08-5bb9-11e5-8c9a-3e9cbcb2d58a.png)

**Comment by sshumilov** [comment]
Looks like bug in dp for skill id 4074 
<skill id="4074" levels="2" name="NPC Haste">
		
		<table name="#abnormalLvls"> 1 2 </table>
		<table name="#magicLvl"> 30 70 </table>
		<table name="#mpConsume"> 14 33 </table>
		<table name="#pAtkSpd"> 1.15 1.33 </table>
		<set name="abnormalLvl" val="#abnormalLvls" />
		<set name="abnormalTime" val="300" />
		<set name="abnormalType" val="ATTACK_TIME_DOWN" />
		<set name="castRange" val="400" />
		<set name="effectPoint" val="100" />
		<set name="effectRange" val="900" />
		<set name="hitTime" val="2000" />
		<set name="icon" val="icon.skill1086" />
		<set name="isMagic" val="1" /> 
		<set name="magicLvl" val="#magicLvl" />
		<set name="mpConsume" val="#mpConsume" />
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="8000" />
		<set name="rideState" val="NONE;STRIDER;WYVERN;WOLF" />
		<set name="targetType" val="ONE" />
		<for>
			<effect name="Buff">
				<mul stat="pAtkSpd" val="#pAtkSpd" />
			</effect>
		</for>
	</skill>

Works after changing target type to "SELF"

**Comment by Zoey76** [comment]
Please check https://github.com/L2J/L2J_Server/tree/feature/ai-refactor

**Comment by Zoey76** [comment]
Fixed in https://github.com/L2J/L2J_Server/commit/170818d22dc716708e103a2586586747bb8833fb
