### ISSUE TITLE
Stakato nest - mobs heal player

### ISSUE THREAD

**Issue by sshumilov** [L2J/L2J_Server#95]
Hi5 stable
L2J_Server rev: 7a2c5132bcd7fb68c4e69d96a12c5cc1081baf58
L2J_DP rev: 86da2832a2a78d297a2f14eb3b50cd4091ebb02c

Cannibalistic Stakato Leader sometimes heals player
![screenshot from 2015-09-17 16 48 24](https://cloud.githubusercontent.com/assets/8612428/9935359/d649b942-5d5e-11e5-8913-7443d5a13e78.png)

**Comment by maneco2** [comment]
It happens the same NPC Haste happened before, but it's hard to happen

**Comment by sshumilov** [comment]
It also happens in imperial tomb location, so, I think, its not a bug of  mob skill, but a bug for all mobs heal skills. I post possible fix for this and for npc haste on forum http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31642

**Comment by Zoey76** [comment]
Issue addressed check http://www.l2jserver.com/forum/viewtopic.php?f=77&t=26415&p=190088#p190088

**Comment by Zoey76** [comment]
Please check https://github.com/L2J/L2J_Server/tree/feature/ai-refactor

**Comment by Zoey76** [comment]
Fixed in https://github.com/L2J/L2J_Server/commit/170818d22dc716708e103a2586586747bb8833fb
