### ISSUE TITLE
Can not talk with some traders(Giran) with geo enabled

### ISSUE THREAD

**Issue by sshumilov** [L2J/L2J_Server#97]
Geo from wiki page https://github.com/L2J/L2J_Server/wiki/Geodata
Grocery store
![screenshot from 2015-09-29 17 39 58](https://cloud.githubusercontent.com/assets/8612428/10167597/d7714d04-66d1-11e5-8363-10861e508fa9.png)
Accessory store
![screenshot from 2015-09-29 17 40 41](https://cloud.githubusercontent.com/assets/8612428/10167613/f03c27e6-66d1-11e5-9393-2c4c61f99e77.png)
Armor store 
![screenshot from 2015-09-29 17 42 22](https://cloud.githubusercontent.com/assets/8612428/10167637/06e155d4-66d2-11e5-8f13-cc0b08334bd4.png)
But from left or right side dialog opens fine(for armor shop)
![screenshot from 2015-09-29 17 42 47](https://cloud.githubusercontent.com/assets/8612428/10167652/18ea79cc-66d2-11e5-9fce-7023131ce6a0.png)

**Comment by BioKryptY** [comment]
Here also happens the same things, not only in Giran but as in other towns as well.

**Comment by Sacrifice78** [comment]
Wich geodata do you have?... last from l2j website?

**Comment by sshumilov** [comment]
Geodata from l2j github wiki

**Comment by Sacrifice78** [comment]
Use geodata that all are using from... https://github.com/L2JGeo/L2J_Geodata_Hi5

**Comment by Zoey76** [comment]
Get geodata from main site

On 29/09/2015, at 14:12, "sshumilov" <notifications@github.com> wrote:

Geodata from l2j github wiki

**Comment by sshumilov** [comment]
Thanx. Works!
![screenshot from 2015-09-30 10 20 00](https://cloud.githubusercontent.com/assets/8612428/10186894/3003bfca-675d-11e5-84a4-617b49c6ec73.png)
