### ISSUE TITLE
L2J Duel Problem [MASTER][LOW]

### ISSUE THREAD

**Issue by maneco2** [L2J/L2J_Server#98]
https://www.youtube.com/watch?v=9HTb3RL3lMs&t=1m25s

**Comment by Sdw-** [comment]
@sshumilov just create the task if party otherwise regenerate right away

**Comment by Zoey76** [comment]
Can someone test @sshumilov's fix?

**Comment by maneco2** [comment]
Dont working :-1: wrong fix

**Comment by sshumilov** [comment]
Something strange... compiles for me
https://youtu.be/RPDsd1rH9Kw

**Comment by Sacrifice78** [comment]
I remember that for me compile perfectly

**Comment by machado-rev** [comment]
Works properly!

**Comment by Zealar** [comment]
https://github.com/L2J/L2J_Server/commit/54f9f147fae29c12776386bb93e950bff48e2fb0
